[tool.poetry]
name = "aoc2024"
version = "0.1.0"
description = ""
authors = ["Mattia Franzin <mattia2700franzin+devs@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
